// 客户管理页 mock 数据。后端接入前由前端独立维护，互不影响 messages 页 mock。

import type { Account } from "@/lib/types/account";
import type { Customer, CustomerStage } from "@/lib/types/customer";

import { STRINGS } from "./strings";

// 让账号页"最近活跃"在 mock 下相对今天具备真实感；改成绝对时间戳后，
// 账号卡片右下角的"X 分钟前"在任何运行日都看得出 recency。
const minutesAgoISO = (m: number) => new Date(Date.now() - m * 60_000).toISOString();

// 7 天伪随机趋势：用一个种子让同一账号每次刷新数据稳定，但数字看起来"有起伏"。
function seedTrend(seed: number, base: number): number[] {
  const out: number[] = [];
  let s = seed;
  for (let i = 0; i < 7; i++) {
    s = (s * 9301 + 49297) % 233_280;
    const v = Math.floor(base * 0.4 + (s / 233_280) * base);
    out.push(v);
  }
  return out;
}

export const MOCK_ACCOUNTS: Account[] = [
  {
    id: "a-bj-zhe",
    name: "北京客服·阿哲",
    colorToken: 3,
    ownerName: "阿哲",
    city: "北京",
    enterprise: "北京科技有限公司",
    verified: true,
    status: "online",
    createdAt: "2024-01-15 09:30",
    customerCount: 1234,
    sessionCount: 2345,
    trend7d: seedTrend(11, 50),
    lastActiveAt: minutesAgoISO(1),
  },
  {
    id: "a-sz-ling",
    name: "深圳销售·阿玲",
    colorToken: 5,
    ownerName: "阿玲",
    city: "深圳",
    enterprise: "深圳创新科技有限公司",
    verified: true,
    status: "online",
    createdAt: "2024-01-14 14:20",
    customerCount: 987,
    sessionCount: 1876,
    trend7d: seedTrend(22, 40),
    lastActiveAt: minutesAgoISO(2),
  },
  {
    id: "a-cd-zhou",
    name: "成都客服·小周",
    colorToken: 4,
    ownerName: "小周",
    city: "成都",
    enterprise: "成都智联科技有限公司",
    verified: true,
    status: "abnormal",
    createdAt: "2024-01-13 11:15",
    customerCount: 658,
    sessionCount: 1234,
    trend7d: seedTrend(33, 35),
    lastActiveAt: minutesAgoISO(30),
  },
  {
    id: "a-gz-bei",
    name: "广州企微·小贝",
    colorToken: 2,
    ownerName: "小贝",
    city: "广州",
    enterprise: "广州云创科技有限公司",
    verified: true,
    status: "online",
    createdAt: "2024-01-12 16:45",
    customerCount: 654,
    sessionCount: 1098,
    trend7d: seedTrend(44, 30),
    lastActiveAt: minutesAgoISO(5),
  },
  {
    id: "a-hz-mei",
    name: "杭州企微·小美",
    colorToken: 1,
    ownerName: "小美",
    city: "杭州",
    enterprise: "杭州未来科技有限公司",
    verified: true,
    status: "offline",
    createdAt: "2024-01-11 10:30",
    customerCount: 432,
    sessionCount: 765,
    trend7d: seedTrend(55, 25),
    lastActiveAt: minutesAgoISO(60 * 48),
  },
  {
    id: "a-nj-fei",
    name: "南京企微·阿菲",
    colorToken: 6,
    ownerName: "阿菲",
    city: "南京",
    enterprise: "南京数智科技有限公司",
    verified: true,
    status: "online",
    createdAt: "2024-01-10 09:20",
    customerCount: 1178,
    sessionCount: 987,
    trend7d: seedTrend(66, 35),
    lastActiveAt: minutesAgoISO(3),
  },
  {
    id: "a-sh-yan",
    name: "上海售前·彦",
    colorToken: 7,
    ownerName: "小彦",
    city: "上海",
    enterprise: "上海前沿信息技术有限公司",
    verified: true,
    status: "online",
    createdAt: "2024-01-09 17:08",
    customerCount: 892,
    sessionCount: 1543,
    trend7d: seedTrend(77, 32),
    lastActiveAt: minutesAgoISO(8),
  },
  {
    id: "a-wh-tong",
    name: "武汉客服·小桐",
    colorToken: 8,
    ownerName: "小桐",
    city: "武汉",
    enterprise: "武汉九章科技有限公司",
    verified: true,
    status: "online",
    createdAt: "2024-01-08 13:42",
    customerCount: 521,
    sessionCount: 832,
    trend7d: seedTrend(88, 22),
    lastActiveAt: minutesAgoISO(15),
  },
  {
    id: "a-xa-bo",
    name: "西安销售·阿博",
    colorToken: 1,
    ownerName: "阿博",
    city: "西安",
    enterprise: "西安长安数字科技有限公司",
    verified: true,
    status: "online",
    createdAt: "2024-01-07 15:55",
    customerCount: 367,
    sessionCount: 612,
    trend7d: seedTrend(99, 18),
    lastActiveAt: minutesAgoISO(40),
  },
  {
    id: "a-tj-jin",
    name: "天津企微·阿瑾",
    colorToken: 2,
    ownerName: "阿瑾",
    city: "天津",
    enterprise: "天津海河智能科技有限公司",
    verified: true,
    status: "online",
    createdAt: "2024-01-06 11:20",
    customerCount: 278,
    sessionCount: 456,
    trend7d: seedTrend(110, 15),
    lastActiveAt: minutesAgoISO(7),
  },
  {
    id: "a-su-ke",
    name: "苏州客服·小柯",
    colorToken: 3,
    ownerName: "小柯",
    city: "苏州",
    enterprise: "苏州姑苏数据有限公司",
    verified: true,
    status: "online",
    createdAt: "2024-01-05 09:48",
    customerCount: 442,
    sessionCount: 691,
    trend7d: seedTrend(121, 20),
    lastActiveAt: minutesAgoISO(11),
  },
  {
    id: "a-cq-le",
    name: "重庆销售·阿乐",
    colorToken: 4,
    ownerName: "阿乐",
    city: "重庆",
    enterprise: "重庆山城智联有限公司",
    verified: false,
    status: "online",
    createdAt: "2024-01-04 14:32",
    customerCount: 198,
    sessionCount: 312,
    trend7d: seedTrend(132, 12),
    lastActiveAt: minutesAgoISO(22),
  },
  {
    id: "a-cs-yu",
    name: "长沙企微·阿宇",
    colorToken: 5,
    ownerName: "阿宇",
    city: "长沙",
    enterprise: "长沙湘江科技有限公司",
    verified: true,
    status: "online",
    createdAt: "2024-01-03 10:10",
    customerCount: 386,
    sessionCount: 543,
    trend7d: seedTrend(143, 16),
    lastActiveAt: minutesAgoISO(6),
  },
  {
    id: "a-xm-tao",
    name: "厦门客服·阿涛",
    colorToken: 6,
    ownerName: "阿涛",
    city: "厦门",
    enterprise: "厦门鹭岛科技有限公司",
    verified: true,
    status: "online",
    createdAt: "2023-12-28 16:24",
    customerCount: 256,
    sessionCount: 389,
    trend7d: seedTrend(154, 14),
    lastActiveAt: minutesAgoISO(9),
  },
  {
    id: "a-qd-han",
    name: "青岛销售·阿翰",
    colorToken: 7,
    ownerName: "阿翰",
    city: "青岛",
    enterprise: "青岛崂山数据有限公司",
    verified: true,
    status: "online",
    createdAt: "2023-12-25 11:48",
    customerCount: 312,
    sessionCount: 478,
    trend7d: seedTrend(165, 17),
    lastActiveAt: minutesAgoISO(14),
  },
  {
    id: "a-nb-ya",
    name: "宁波企微·阿雅",
    colorToken: 8,
    ownerName: "阿雅",
    city: "宁波",
    enterprise: "宁波东海智科有限公司",
    verified: false,
    status: "abnormal",
    createdAt: "2023-12-20 09:30",
    customerCount: 189,
    sessionCount: 267,
    trend7d: seedTrend(176, 10),
    lastActiveAt: minutesAgoISO(60 * 5),
  },
  {
    id: "a-hf-yi",
    name: "合肥客服·阿弈",
    colorToken: 1,
    ownerName: "阿弈",
    city: "合肥",
    enterprise: "合肥科教智联有限公司",
    verified: true,
    status: "online",
    createdAt: "2023-12-15 13:18",
    customerCount: 234,
    sessionCount: 354,
    trend7d: seedTrend(187, 13),
    lastActiveAt: minutesAgoISO(28),
  },
  {
    id: "a-fz-rui",
    name: "福州销售·阿瑞",
    colorToken: 2,
    ownerName: "阿瑞",
    city: "福州",
    enterprise: "福州榕城信息有限公司",
    verified: true,
    status: "online",
    createdAt: "2023-12-08 15:02",
    customerCount: 167,
    sessionCount: 245,
    trend7d: seedTrend(198, 11),
    lastActiveAt: minutesAgoISO(12),
  },
];

export const MOCK_FOLLOWERS = ["小美", "阿哲", "阿玲", "阿菲", "小贝", "小周", "未分配"] as const;

export const TAG_PRESETS = [
  "重点客户",
  "VIP",
  "高意向",
  "续约",
  "合同已签",
  "新加好友",
  "待回访",
  "黑名单",
] as const;

interface SeedRow {
  name: string;
  channel: string;
  accountId: string;
  tags: string[];
  remark: string;
  phone: string;
  weChat: string;
  company: string;
  source: string;
  addedAt: string;
  follower: string;
  starred?: boolean;
  lastContactAt?: string | null;
  followUpReason?: string;
  timeline?: { at: string; text: string }[];
}

const SEED: SeedRow[] = [
  {
    name: "林知言",
    channel: "微信",
    accountId: "a-hz-mei",
    tags: ["重点客户", "续约"],
    remark:
      "Q4 续约洽谈：客户希望在 12 月前完成新合同；技术对接已对齐至 v2.3 SDK，运维负责人是张工。",
    phone: "186****0421",
    weChat: "linzhiyan_wx",
    company: "知言科技",
    source: "公司官网",
    addedAt: "2024-05-20 10:15",
    follower: "阿玲",
    starred: true,
    lastContactAt: "2026-05-01T14:08:00+08:00",
    timeline: [
      { at: "2024-09-20", text: "标签更新：续约" },
      { at: "2024-08-12", text: "移交至 阿玲 跟进" },
      { at: "2024-05-20", text: "通过公司官网添加" },
    ],
  },
  {
    name: "陈雪舟",
    channel: "微信",
    accountId: "a-bj-zhe",
    tags: ["高意向"],
    remark: "通过抖音看到我们直播课，咨询企业版方案。",
    phone: "138****1102",
    weChat: "snowboat_chen",
    company: "东岸资本",
    source: "抖音线索",
    addedAt: "2026-04-22 09:32",
    follower: "阿哲",
    starred: false,
    lastContactAt: "2026-05-02T19:45:00+08:00",
    timeline: [{ at: "2026-04-22", text: "通过抖音线索添加" }],
  },
  {
    name: "王锐",
    channel: "微信",
    accountId: "a-sz-ling",
    tags: ["VIP", "高意向"],
    remark: "已签约一个企业账户；正在评估扩量。",
    phone: "176****1182",
    weChat: "ray_wang",
    company: "华讯通",
    source: "微信搜索",
    addedAt: "2024-03-11 11:08",
    follower: "阿玲",
    starred: true,
    lastContactAt: "2026-05-03T08:55:00+08:00",
    timeline: [
      { at: "2026-04-30", text: "标签更新：VIP" },
      { at: "2024-03-11", text: "通过微信搜索添加" },
    ],
  },
  {
    name: "韩雪",
    channel: "微信",
    accountId: "a-hz-mei",
    tags: ["合同已签"],
    remark: "三年期年框已落，关注续费节奏。",
    phone: "139****8821",
    weChat: "han_xue",
    company: "蓝湾医药",
    source: "转介绍",
    addedAt: "2023-11-04 16:50",
    follower: "小美",
    starred: false,
    lastContactAt: "2026-05-02T11:30:00+08:00",
    timeline: [{ at: "2023-11-04", text: "由 王锐 转介绍" }],
  },
  {
    name: "沈砚之",
    channel: "微信",
    accountId: "a-nj-fei",
    tags: ["新加好友"],
    remark: "意向不明，先做一次破冰。",
    phone: "131****5510",
    weChat: "shen_yz",
    company: "夜湖文化",
    source: "转介绍",
    addedAt: "2026-05-02 16:20",
    follower: "未分配",
    starred: false,
    lastContactAt: null,
    followUpReason: STRINGS.followUpReason.newAssign,
    timeline: [{ at: "2026-05-02", text: "由 阿菲 添加" }],
  },
  {
    name: "苏皖",
    channel: "微信",
    accountId: "a-gz-bei",
    tags: ["高意向"],
    remark: "在体验试用版，关心多账号管理能力。",
    phone: "182****0011",
    weChat: "wan_su",
    company: "云涟科技",
    source: "公司官网",
    addedAt: "2026-04-29 08:08",
    follower: "小贝",
    starred: true,
    lastContactAt: "2026-04-30T10:14:00+08:00",
    followUpReason: STRINGS.followUpReason.noReply(72),
    timeline: [{ at: "2026-04-29", text: "通过官网线索添加" }],
  },
  {
    name: "周嘉行",
    channel: "微信",
    accountId: "a-cd-zhou",
    tags: ["待回访"],
    remark: "上次沟通到合同条款，等法务回执。",
    phone: "150****6603",
    weChat: "jx_zhou",
    company: "川合资本",
    source: "线下沙龙",
    addedAt: "2024-12-16 19:02",
    follower: "小周",
    starred: false,
    lastContactAt: "2026-04-25T15:00:00+08:00",
    followUpReason: STRINGS.followUpReason.longSilence,
    timeline: [{ at: "2024-12-16", text: "线下沙龙添加" }],
  },
  {
    name: "顾岚",
    channel: "微信",
    accountId: "a-hz-mei",
    tags: ["重点客户"],
    remark: "全国连锁医美品牌，跨账号回访。",
    phone: "159****7702",
    weChat: "lan_gu",
    company: "岚桐医美",
    source: "客户介绍",
    addedAt: "2024-07-21 13:42",
    follower: "小美",
    starred: true,
    lastContactAt: "2026-05-02T22:01:00+08:00",
    timeline: [{ at: "2024-07-21", text: "由 韩雪 转介绍" }],
  },
  {
    name: "汤砚",
    channel: "微信",
    accountId: "a-bj-zhe",
    tags: [],
    remark: "",
    phone: "182****9009",
    weChat: "tang_yan",
    company: "鸿砚信息",
    source: "公司官网",
    addedAt: "2026-04-30 09:00",
    follower: "阿哲",
    starred: false,
    lastContactAt: null,
    timeline: [{ at: "2026-04-30", text: "通过官网线索添加" }],
  },
  {
    name: "范行知",
    channel: "微信",
    accountId: "a-sz-ling",
    tags: ["高意向", "新加好友"],
    remark: "对接技术 PoC，下周演示。",
    phone: "133****7841",
    weChat: "fanxz",
    company: "深谷智能",
    source: "线下沙龙",
    addedAt: "2026-05-03 09:14",
    follower: "阿玲",
    starred: false,
    lastContactAt: "2026-05-03T09:20:00+08:00",
    followUpReason: STRINGS.followUpReason.newAssign,
    timeline: [{ at: "2026-05-03", text: "线下沙龙添加" }],
  },
  {
    name: "纪向北",
    channel: "微信",
    accountId: "a-cd-zhou",
    tags: ["合同已签", "续约"],
    remark: "明年 Q1 续约，重点跟进市场预算。",
    phone: "152****3315",
    weChat: "ji_xb",
    company: "北纬实验室",
    source: "客户介绍",
    addedAt: "2023-08-09 17:25",
    follower: "小周",
    starred: false,
    lastContactAt: "2026-05-01T11:24:00+08:00",
    timeline: [{ at: "2023-08-09", text: "由 王锐 转介绍" }],
  },
  {
    name: "于知微",
    channel: "微信",
    accountId: "a-nj-fei",
    tags: ["重点客户", "VIP"],
    remark: "南京头部 SaaS 客户。",
    phone: "139****0902",
    weChat: "zhiwei_yu",
    company: "微合信息",
    source: "微信搜索",
    addedAt: "2023-04-19 15:18",
    follower: "阿菲",
    starred: true,
    lastContactAt: "2026-05-02T17:10:00+08:00",
    timeline: [{ at: "2023-04-19", text: "通过微信搜索添加" }],
  },
  {
    name: "贺秋月",
    channel: "微信",
    accountId: "a-gz-bei",
    tags: ["待回访"],
    remark: "上一轮试用反馈良好，等他汇报领导。",
    phone: "187****6612",
    weChat: "qiuyue_he",
    company: "南粤教育",
    source: "公司官网",
    addedAt: "2024-09-11 10:34",
    follower: "小贝",
    starred: false,
    lastContactAt: "2026-04-26T09:00:00+08:00",
    followUpReason: STRINGS.followUpReason.longSilence,
    timeline: [{ at: "2024-09-11", text: "通过公司官网添加" }],
  },
  {
    name: "苗远",
    channel: "微信",
    accountId: "a-hz-mei",
    tags: ["新加好友"],
    remark: "",
    phone: "133****8821",
    weChat: "yuan_miao",
    company: "",
    source: "微信搜索",
    addedAt: "2026-04-30 18:42",
    follower: "小美",
    starred: false,
    lastContactAt: null,
    timeline: [{ at: "2026-04-30", text: "通过微信搜索添加" }],
  },
  {
    name: "盛清",
    channel: "微信",
    accountId: "a-sz-ling",
    tags: ["VIP"],
    remark: "高净值客户，季度回访。",
    phone: "136****1010",
    weChat: "qing_sheng",
    company: "盛景资本",
    source: "客户介绍",
    addedAt: "2024-02-02 13:40",
    follower: "阿玲",
    starred: true,
    lastContactAt: "2026-05-01T10:25:00+08:00",
    timeline: [{ at: "2024-02-02", text: "由 周嘉行 转介绍" }],
  },
  {
    name: "陆江南",
    channel: "微信",
    accountId: "a-bj-zhe",
    tags: ["高意向"],
    remark: "希望听一次产品 deep dive。",
    phone: "180****4422",
    weChat: "jn_lu",
    company: "江南文化",
    source: "公司官网",
    addedAt: "2026-04-25 14:09",
    follower: "阿哲",
    starred: false,
    lastContactAt: "2026-04-29T20:18:00+08:00",
    followUpReason: STRINGS.followUpReason.noReply(96),
    timeline: [{ at: "2026-04-25", text: "通过公司官网添加" }],
  },
  {
    name: "邵岸",
    channel: "微信",
    accountId: "a-cd-zhou",
    tags: [],
    remark: "",
    phone: "189****0231",
    weChat: "an_shao",
    company: "岸岭传媒",
    source: "微信搜索",
    addedAt: "2024-10-30 09:21",
    follower: "小周",
    starred: false,
    lastContactAt: "2026-05-02T08:50:00+08:00",
    timeline: [{ at: "2024-10-30", text: "通过微信搜索添加" }],
  },
  {
    name: "齐韫",
    channel: "微信",
    accountId: "a-nj-fei",
    tags: ["合同已签"],
    remark: "",
    phone: "176****8801",
    weChat: "yun_qi",
    company: "韫合科技",
    source: "客户介绍",
    addedAt: "2025-06-18 16:45",
    follower: "阿菲",
    starred: false,
    lastContactAt: "2026-04-30T13:00:00+08:00",
    timeline: [{ at: "2025-06-18", text: "由 林知言 转介绍" }],
  },
  {
    name: "魏星言",
    channel: "微信",
    accountId: "a-gz-bei",
    tags: ["新加好友", "高意向"],
    remark: "",
    phone: "189****6601",
    weChat: "xy_wei",
    company: "星言传媒",
    source: "线下沙龙",
    addedAt: "2026-05-01 10:15",
    follower: "小贝",
    starred: false,
    lastContactAt: "2026-05-01T16:33:00+08:00",
    timeline: [{ at: "2026-05-01", text: "线下沙龙添加" }],
  },
  {
    name: "钟书淮",
    channel: "微信",
    accountId: "a-hz-mei",
    tags: ["待回访"],
    remark: "希望对接他们财务系统。",
    phone: "159****7724",
    weChat: "shuhuai_z",
    company: "淮云软件",
    source: "公司官网",
    addedAt: "2024-04-15 11:00",
    follower: "小美",
    starred: false,
    lastContactAt: "2026-04-22T17:45:00+08:00",
    followUpReason: STRINGS.followUpReason.longSilence,
    timeline: [{ at: "2024-04-15", text: "通过公司官网添加" }],
  },
];

// 业务进展（阶段 / 成交 / 下次跟进）按姓名对齐到 SEED；为了视觉演示混入今天/明天/超期等。
// 假设当前日期约为 2026-05-04（与 lastContactAt 对齐）。
interface BizProgress {
  stage?: CustomerStage;
  dealAmount?: number;
  contractSignedAt?: string;
  nextFollowUpAt?: string;
}

const BIZ_BY_NAME: Record<string, BizProgress> = {
  林知言: {
    stage: "deal-won",
    dealAmount: 360000,
    contractSignedAt: "2024-08-01",
    nextFollowUpAt: "2026-05-06 14:00",
  },
  陈雪舟: { stage: "intent", nextFollowUpAt: "2026-05-06 10:00" },
  王锐: {
    stage: "deal-won",
    dealAmount: 85000,
    contractSignedAt: "2024-04-10",
    nextFollowUpAt: "2026-05-05 16:00",
  },
  韩雪: {
    stage: "deal-won",
    dealAmount: 120000,
    contractSignedAt: "2023-11-04",
    nextFollowUpAt: "2026-05-04 09:00",
  },
  沈砚之: { stage: "lead", nextFollowUpAt: "2026-05-05 10:00" },
  苏皖: { stage: "intent", nextFollowUpAt: "2026-05-03 14:00" },
  周嘉行: { stage: "negotiating", nextFollowUpAt: "2026-05-02 11:00" },
  顾岚: {
    stage: "deal-won",
    dealAmount: 260000,
    contractSignedAt: "2024-09-15",
    nextFollowUpAt: "2026-05-04 11:00",
  },
  汤砚: { stage: "lead", nextFollowUpAt: "2026-05-05 09:30" },
  范行知: { stage: "intent", nextFollowUpAt: "2026-05-04 15:00" },
  纪向北: {
    stage: "deal-won",
    dealAmount: 180000,
    contractSignedAt: "2023-12-20",
    nextFollowUpAt: "2026-05-15 10:00",
  },
  于知微: {
    stage: "deal-won",
    dealAmount: 420000,
    contractSignedAt: "2023-06-01",
    nextFollowUpAt: "2026-06-01 14:00",
  },
  贺秋月: { stage: "negotiating", nextFollowUpAt: "2026-05-08 16:00" },
  苗远: { stage: "lead" },
  盛清: {
    stage: "deal-won",
    dealAmount: 98000,
    contractSignedAt: "2024-03-15",
    nextFollowUpAt: "2026-05-12 10:00",
  },
  陆江南: { stage: "intent", nextFollowUpAt: "2026-05-02 14:00" },
  邵岸: { stage: "contacting" },
  齐韫: {
    stage: "deal-won",
    dealAmount: 150000,
    contractSignedAt: "2025-08-22",
    nextFollowUpAt: "2026-05-20 14:00",
  },
  魏星言: { stage: "intent", nextFollowUpAt: "2026-05-06 10:30" },
  钟书淮: { stage: "negotiating", nextFollowUpAt: "2026-04-28 14:00" },
};

// 把若干"较新的"客户的 addedAt 重写为相对今天的近 7 日时间戳。这样无论 app
// 在哪一天运行，账号页 KPI 与每张卡片的"今日新增 / 近 7 日趋势"都能体现 recency。
// 跨账号铺开，让多张卡片都有非零数字。
const daysAgoStamp = (d: number, hour = 9) =>
  new Date(Date.now() - d * 86_400_000 + hour * 3_600_000)
    .toISOString()
    .replace("T", " ")
    .slice(0, 16);

const RECENT_ADDED_AT: Record<string, string> = {
  陈雪舟: daysAgoStamp(0, 9), // 今日 - a-bj-zhe
  沈砚之: daysAgoStamp(0, 16), // 今日 - a-nj-fei
  范行知: daysAgoStamp(1, 14), // 昨日 - a-sz-ling
  汤砚: daysAgoStamp(2, 10), // 2 天前 - a-bj-zhe
  魏星言: daysAgoStamp(3, 11), // 3 天前 - a-gz-bei
  苏皖: daysAgoStamp(5, 8), // 5 天前 - a-gz-bei
  苗远: daysAgoStamp(6, 18), // 6 天前 - a-hz-mei
};

export const MOCK_CUSTOMERS: Customer[] = SEED.map((row, i) => ({
  id: `cust-${i + 1}`,
  name: row.name,
  channel: row.channel,
  account: MOCK_ACCOUNTS.find((a) => a.id === row.accountId)?.name ?? row.accountId,
  accountId: row.accountId,
  tags: row.tags,
  remark: row.remark,
  phone: row.phone,
  weChat: row.weChat,
  company: row.company,
  source: row.source,
  addedAt: RECENT_ADDED_AT[row.name] ?? row.addedAt,
  follower: row.follower,
  starred: row.starred ?? false,
  lastContactAt: row.lastContactAt ?? null,
  followUpReason: row.followUpReason,
  timeline: row.timeline,
  ...BIZ_BY_NAME[row.name],
}));

/** 客户最近会话（最多 N 条），用于详情侧栏的"最近会话"段；mock 仅给少量。 */
export interface CustomerRecentMessage {
  customerId: string;
  direction: "in" | "out";
  text: string;
  sentAt: string;
}

export const MOCK_RECENT_MESSAGES: CustomerRecentMessage[] = [
  {
    customerId: "cust-1",
    direction: "in",
    text: "方案我们整体没问题，就是要走法务流程，可能要多 3-5 个工作日。",
    sentAt: "2026-05-01T14:05:00+08:00",
  },
  {
    customerId: "cust-1",
    direction: "out",
    text: "好的，我们这边先准备 v2.3 的合同附件，等您法务有反馈我们一起对一遍。",
    sentAt: "2026-05-01T14:08:00+08:00",
  },
  {
    customerId: "cust-3",
    direction: "in",
    text: "下周 Demo 是几点？我先把产品和 IT 拉齐到会议。",
    sentAt: "2026-05-03T08:50:00+08:00",
  },
  {
    customerId: "cust-3",
    direction: "out",
    text: "周三 14:30 - 15:30，链接我提前一天发您。",
    sentAt: "2026-05-03T08:55:00+08:00",
  },
  {
    customerId: "cust-2",
    direction: "in",
    text: "你们企业版能先发个简版报价吗？",
    sentAt: "2026-05-02T19:42:00+08:00",
  },
];
