// 客户管理页文案，集中维护，方便后续接入 i18n。

export const STRINGS = {
  page: {
    title: "客户管理",
    subtitle: "管理你账号下的所有客户",
  },
  tabs: {
    all: "全部客户",
    key: "重点客户",
    todayNew: "今日新增",
    stale30d: "30天未跟进",
    pendingSign: "待签约客户",
    lost: "流失客户",
  },
  toolbar: {
    searchPlaceholder: "搜索客户名称、手机号、企业名称、标签等",
    accountFilter: "全部账号",
    stageFilter: "客户阶段",
    tagFilter: "标签",
    followUpFilter: "跟进状态",
    moreFilters: "更多筛选",
    reset: "重置",
    newCustomer: "新增客户",
    viewToggle: "切换视图",
    export: "导出",
    sortLabel: "排序",
    sortMenuTitle: "排序方式",
    enterBulk: "批量",
    exitBulk: "退出批量",
    bulkActions: "批量操作",
    filtersTrigger: "筛选",
  },
  sort: {
    lastContact: "按跟进时间",
    addedAt: "按添加时间",
    company: "按公司",
    follower: "按跟进人",
  },
  rowMore: {
    star: "关注",
    unstar: "取消关注",
    chat: "发起会话",
    edit: "编辑",
    more: "更多",
  },
  accountChips: {
    label: "账号筛选",
    allAccounts: "全部账号",
  },
  list: {
    selectAll: (n: number) => `选择当前视图全部 ${n} 位客户`,
    overflowTagsLabel: (n: number) => `+${n}`,
    columnCustomer: "客户名称",
    columnAccount: "所属账号",
    columnStage: "客户阶段",
    columnFollowUp: "跟进状态",
    columnTags: "标签",
    columnLastContact: "最近跟进",
    columnActions: "操作",
  },
  pagination: {
    total: (n: number) => `共 ${n} 条`,
    pageSize: (n: number) => `${n} 条/页`,
    prev: "上一页",
    next: "下一页",
    jumpPrefix: "前往",
    jumpSuffix: "页",
    jumpAria: "跳转到指定页",
  },
  emptyStates: {
    all: {
      title: "暂无客户",
      hint: "等账号添加好友后，客户会出现在这里。",
    },
    key: {
      title: "暂无重点客户",
      hint: "把客户标记为「重点客户」或设为 A 级即可加入此视图。",
    },
    todayNew: {
      title: "今天还没有新增客户",
      hint: "新加好友会自动出现在这里。",
    },
    stale30d: {
      title: "近 30 天客户都已跟进",
      hint: "干得漂亮 ✨",
    },
    pendingSign: {
      title: "暂无待签约客户",
      hint: "进入「谈单中」阶段的客户会出现在这里。",
    },
    lost: {
      title: "暂无流失客户",
      hint: "标记为「已流失」的客户会出现在这里。",
    },
    detail: {
      title: "选择左侧客户查看详情",
      hint: "点击列表中任意一行。",
    },
    detailTabPlaceholder: "敬请期待",
  },
  detail: {
    title: "客户详情",
    sectionTags: "标签",
    sectionNote: "备注",
    sectionContact: "联系方式",
    sectionContactInfo: "联系人信息",
    sectionRecentMessages: "最近会话",
    sectionTimeline: "客户轨迹",
    keyCustomerChip: "重点客户",
    subTabs: {
      info: "客户信息",
      followUp: "跟进记录",
      contacts: "相关联系人",
      orders: "相关订单",
      more: "更多",
    },
    statsCards: {
      stage: "客户阶段",
      followUp: "跟进状态",
      dealAmount: "成交金额",
      level: "客户级别",
    },
    statusCard: {
      stage: "阶段",
      dealAmount: "成交金额",
      contractSignedAt: "签约时间",
      nextFollowUp: "下次跟进",
      empty: "—",
      overdueBadge: "超期",
    },
    stageLabels: {
      lead: "新客户",
      contacting: "跟进中",
      intent: "意向",
      negotiating: "谈单中",
      "deal-won": "成交",
      "deal-lost": "已流失",
    },
    followUpStatusLabels: {
      pending: "待跟进",
      "in-progress": "跟进中",
      done: "已跟进",
    },
    levelLabels: {
      A: "A",
      B: "B",
      C: "C",
      D: "D",
    },
    fields: {
      phone: "手机号码",
      weChat: "微信号",
      industry: "所属行业",
      company: "公司名称",
      region: "所在地区",
      address: "详细地址",
      tags: "客户标签",
      remark: "备注",
      source: "客户来源",
      addedAt: "添加时间",
      follower: "负责人",
      account: "归属账号",
    },
    actions: {
      openChat: "打开会话",
      openChatDisabled: "尚无会话",
      edit: "编辑",
      saveEdit: "保存",
      cancelEdit: "取消",
      starOn: "★ 关注",
      starOff: "已关注",
      more: "更多",
      startChat: "发起会话",
      editCustomer: "编辑客户",
      followUpHistory: "跟进记录",
    },
    addTag: "+ 添加标签",
    addTagPlaceholder: "输入标签后回车",
    notePlaceholder: "为这位客户写一些备注…",
    noteEmpty: "暂无备注",
    expand: "展开",
    collapse: "收起",
    seeAllMessages: "查看全部 →",
    emptyDealAmount: "—",
  },
  bulk: {
    barTitle: (n: number) => `已选 ${n} 位客户`,
    cancel: "取消",
    addRemoveTag: "标签",
    reassign: "移交跟进人",
    starToggle: (allStarred: boolean) => (allStarred ? "取消关注" : "关注"),
    exportCsv: "导出 CSV",
    addRemoveTagDialog: {
      title: "为选中客户更新标签",
      add: "添加这些标签",
      remove: "移除这些标签",
      submit: "应用",
      empty: "请先在右侧选择标签。",
    },
    reassignDialog: {
      title: "移交跟进人",
      submit: "移交",
    },
    csvFileName: "customers",
  },
  toasts: {
    tagsUpdated: (n: number) => `已为 ${n} 位客户更新标签`,
    reassigned: (n: number, to: string) => `已将 ${n} 位客户移交给 ${to}`,
    starred: (n: number) => `已关注 ${n} 位客户`,
    unstarred: (n: number) => `已取消关注 ${n} 位客户`,
    exported: (n: number) => `已导出 ${n} 位客户`,
    newCustomerStub: "新增客户功能正在开发中",
    exportStub: "导出功能正在开发中",
    viewToggleStub: "视图切换功能正在开发中",
  },
  followUpReason: {
    noReply: (hours: number) => `未回复 ${hours}h`,
    newAssign: "新分配",
    longSilence: "长期未联系",
  },
} as const;
