// 客户管理页文案，集中维护，方便后续接入 i18n。

export const STRINGS = {
  page: {
    title: "客户",
    subtitle: "管理你账号下的所有客户",
  },
  tabs: {
    all: "全部",
    needsFollowUp: "待跟进",
    newFriend: "新加好友",
    starred: "我的关注",
  },
  toolbar: {
    searchPlaceholder: "搜索客户、联系人、标签、备注等",
    tagFilter: "标签",
    sortLabel: "排序",
    sortMenuTitle: "排序方式",
    enterBulk: "批量",
    exitBulk: "退出批量",
    bulkActions: "批量操作",
    filtersTrigger: "筛选",
  },
  sort: {
    lastContact: "按跟进时间",
    addedAt: "按添加时间",
    company: "按公司",
    follower: "按跟进人",
  },
  rowMore: {
    star: "关注",
    unstar: "取消关注",
  },
  accountChips: {
    label: "账号筛选",
    allAccounts: "全部账号",
  },
  list: {
    selectAll: (n: number) => `选择当前视图全部 ${n} 位客户`,
    overflowTagsLabel: (n: number) => `+${n}`,
    columnCustomer: "客户信息",
    columnStage: "客户阶段",
    columnNextFollowUp: "下次跟进",
    columnLastContact: "最近联系",
    columnFollower: "跟进人",
  },
  emptyStates: {
    all: {
      title: "暂无客户",
      hint: "等账号添加好友后，客户会出现在这里。",
    },
    needsFollowUp: {
      title: "所有客户都已跟进",
      hint: "干得漂亮 ✨",
    },
    newFriend: {
      title: "最近 7 天没有新加的好友",
      hint: "新好友会自动出现在这里。",
    },
    starred: {
      title: "还没有关注的客户",
      hint: "点击客户行左侧的星标即可加入此视图。",
    },
    detail: {
      title: "选择左侧客户查看详情",
      hint: "点击列表中任意一行。",
    },
  },
  detail: {
    sectionTags: "标签",
    sectionNote: "备注",
    sectionContact: "联系方式",
    sectionRecentMessages: "最近会话",
    sectionTimeline: "客户轨迹",
    statusCard: {
      stage: "阶段",
      dealAmount: "成交金额",
      contractSignedAt: "签约时间",
      nextFollowUp: "下次跟进",
      empty: "—",
      overdueBadge: "超期",
    },
    stageLabels: {
      lead: "新客户",
      contacting: "跟进中",
      intent: "意向",
      negotiating: "谈单中",
      "deal-won": "已成交",
      "deal-lost": "已流失",
    },
    fields: {
      weChat: "微信",
      phone: "手机",
      company: "公司",
      source: "来源",
      addedAt: "添加时间",
      follower: "负责人",
      account: "归属账号",
    },
    actions: {
      openChat: "打开会话",
      openChatDisabled: "尚无会话",
      edit: "编辑",
      saveEdit: "保存",
      cancelEdit: "取消",
      starOn: "★ 关注",
      starOff: "已关注",
      more: "更多",
    },
    addTag: "+ 添加标签",
    addTagPlaceholder: "输入标签后回车",
    notePlaceholder: "为这位客户写一些备注…",
    noteEmpty: "暂无备注",
    expand: "展开",
    collapse: "收起",
    seeAllMessages: "查看全部 →",
  },
  bulk: {
    barTitle: (n: number) => `已选 ${n} 位客户`,
    cancel: "取消",
    addRemoveTag: "标签",
    reassign: "移交跟进人",
    starToggle: (allStarred: boolean) => (allStarred ? "取消关注" : "关注"),
    exportCsv: "导出 CSV",
    addRemoveTagDialog: {
      title: "为选中客户更新标签",
      add: "添加这些标签",
      remove: "移除这些标签",
      submit: "应用",
      empty: "请先在右侧选择标签。",
    },
    reassignDialog: {
      title: "移交跟进人",
      submit: "移交",
    },
    csvFileName: "customers",
  },
  toasts: {
    tagsUpdated: (n: number) => `已为 ${n} 位客户更新标签`,
    reassigned: (n: number, to: string) => `已将 ${n} 位客户移交给 ${to}`,
    starred: (n: number) => `已关注 ${n} 位客户`,
    unstarred: (n: number) => `已取消关注 ${n} 位客户`,
    exported: (n: number) => `已导出 ${n} 位客户`,
  },
  followUpReason: {
    noReply: (hours: number) => `未回复 ${hours}h`,
    newAssign: "新分配",
    longSilence: "长期未联系",
  },
} as const;
