#!/usr/bin/env bash
# 本地启动 chathub-relay,带 downstream / push 两路结构化日志。
#
# 用法:
#   scripts/run-relay-local.sh                    # 默认 debug 跑
#   scripts/run-relay-local.sh --release          # 透传 cargo 参数
#   RUST_LOG=trace scripts/run-relay-local.sh     # 覆盖日志级别
#   RELAY_DOWNSTREAM_URL=http://x scripts/run-relay-local.sh   # 覆盖下游地址
#
# 首次运行会在 scripts/.env.local 中持久化 RELAY_REFRESH_HASH_PEPPER,
# 之后复用,避免每次重启都让所有 refresh_token 失效。

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env.local"

# 1. 加载或生成持久化 env(主要是 pepper)
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "[relay-local] generating ${ENV_FILE} (first run)"
  PEPPER="$(openssl rand -hex 32)"
  cat > "${ENV_FILE}" <<EOF
# Auto-generated by scripts/run-relay-local.sh — local dev only.
# 改 pepper = invalidate 所有 refresh_token。
RELAY_REFRESH_HASH_PEPPER=${PEPPER}
EOF
fi
# shellcheck disable=SC1090
set -a; source "${ENV_FILE}"; set +a

# 2. dev 默认值(外部 env / .env.local 优先)
# 2026-05-16:RELAY_DOWNSTREAM_SECRET 已下线(改走客户端 token 透传)
export RELAY_ALLOW_HTTP=true
export RELAY_DOWNSTREAM_URL="${RELAY_DOWNSTREAM_URL:-http://127.0.0.1:8080}"
export RELAY_PUSH_SECRET="${RELAY_PUSH_SECRET:-push-secret}"
# OAuth2 Basic client auth(default 都是 rh_wxchat,生产部署可 override)
export RELAY_OAUTH_CLIENT_ID="${RELAY_OAUTH_CLIENT_ID:-rh_wxchat}"
export RELAY_OAUTH_CLIENT_SECRET="${RELAY_OAUTH_CLIENT_SECRET:-rh_wxchat}"
export RELAY_GRPC_ADDR="${RELAY_GRPC_ADDR:-127.0.0.1:50051}"
export RELAY_PUSH_ADDR="${RELAY_PUSH_ADDR:-127.0.0.1:50052}"
export RELAY_DB_PATH="${RELAY_DB_PATH:-${REPO_ROOT}/relay.db}"

# 3. 日志默认:全局 info,downstream/push 两路打到 debug
export RUST_LOG="${RUST_LOG:-info,chathub_relay::downstream=debug,chathub_relay::push=debug}"

echo "[relay-local] grpc=${RELAY_GRPC_ADDR}  push=${RELAY_PUSH_ADDR}"
echo "[relay-local] downstream=${RELAY_DOWNSTREAM_URL}"
echo "[relay-local] db=${RELAY_DB_PATH}"
echo "[relay-local] RUST_LOG=${RUST_LOG}"

cd "${REPO_ROOT}"
exec cargo run -p chathub-relay --bin chathub-relay "$@"
